version: 2
registries:
  maven-repository-repo-dustplanet-de:
    type: maven-repository
    url: https://repo.dustplanet.de
    username: jenkins
    password: "${{secrets.MAVEN_REPOSITORY_REPO_DUSTPLANET_DE_PASSWORD}}"

updates:
- package-ecosystem: "maven"
  directory: "/"
  schedule:
    interval: daily
  registries:
    - maven-repository-repo-dustplanet-de
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
