# For help please refer to http://dev.bukkit.org/bukkit-plugins/cookme/
configuration:
  permissions: true
  messages: true
  duration:
    min: 15
    max: 30
  cooldown: 30
  debug: false
  preventVanillaPoison: false
  randomEffectStrength: true
effects:
  damage: 8.0
  death: 4.0
  venom: 8.0
  hungervenom: 8.0
  hungerdecrease: 8.0
  confusion: 8.0
  blindness: 8.0
  weakness: 8.0
  slowness: 8.0
  slowness_blocks: 8.0
  instant_damage: 8.0
  refusing: 8.0
  wither: 8.0
effectStrength:
  venom: 8
  hungervenom: 8
  confusion: 8
  blindness: 8
  weakness: 8
  slowness: 8
  slowness_blocks: 8
  instant_damage: 8
  wither: 8
food:
- RAW_BEEF
- RAW_CHICKEN
- RAW_FISH
- PORK
- ROTTEN_FLESH
