# For help please refer to https://dev.bukkit.org/projects/cookme/
configuration:
  permissions: true
  messages: true
  duration:
    min: 15
    max: 30
  cooldown: 30
  debug: false
  preventVanillaPoison: false
  randomEffectStrength: true
effects:
  damage: 6.9
  death: 4.0
  venom: 6.9
  hungervenom: 6.9
  hungerdecrease: 6.9
  confusion: 6.9
  blindness: 6.9
  weakness: 6.9
  slowness: 6.9
  slowness_blocks: 6.9
  instant_damage: 6.9
  refusing: 6.9
  wither: 6.9
  levitation: 6.9
  unluck: 6.9
effectStrength:
  venom: 8
  hungervenom: 8
  confusion: 8
  blindness: 8
  weakness: 8
  slowness: 8
  slowness_blocks: 8
  instant_damage: 8
  wither: 8
  levitation: 8
  unluck: 8
food:
- BEEF
- CHICKEN
- PORKCHOP
- ROTTEN_FLESH
- MUTTON
- RABBIT
- COD
- SALMON
- PUFFERFISH
