# For help please refer to https://dev.bukkit.org/projects/cookme/

configuration:
  permissions: true
  messages: true
  duration:
    min: 15
    max: 30
  cooldown: 30
  debug: false
  preventVanillaPoison: false
  randomEffectStrength: true
effects:
  damage: 6.25
  death: 6.25
  venom: 6.25
  hungervenom: 6.25
  hungerdecrease: 6.25
  confusion: 6.25
  blindness: 6.25
  weakness: 6.25
  slowness: 6.25
  slowness_blocks: 6.25
  instant_damage: 6.25
  refusing: 6.25
  wither: 6.25
  levitation: 6.25
  unluck: 6.25
  bad_omen: 6.25
effectStrength:
  venom: 8
  hungervenom: 8
  confusion: 8
  blindness: 8
  weakness: 8
  slowness: 8
  slowness_blocks: 8
  instant_damage: 8
  wither: 8
  levitation: 8
  unluck: 8
  bad_omen: 8
food:
- BEEF
- CHICKEN
- PORKCHOP
- ROTTEN_FLESH
- MUTTON
- RABBIT
- COD
- SALMON
- PUFFERFISH
