# For help please refer to http://bit.ly/cookmebukkitdev or http://bit.ly/cookmebukkit
configuration:
  permissions: true
  messages: true
  duration:
    min: 15
    max: 30
  noBlocks: true
  cooldown: 30
effects:
  damage: 8.7
  death: 4.3
  venom: 8.7
  hungervenom: 8.7
  hungerdecrease: 8.7
  confusion: 8.7
  blindness: 8.7
  weakness: 8.7
  slowness: 8.7
  slowness_blocks: 8.7
  instant_damage: 8.7
  refusing: 8.7
food:
- RAW_BEEF
- RAW_CHICKEN
- RAW_FISH
- PORK
- ROTTEN_FLESH