# For help please refer to http://bit.ly/cookmebukkitdev or http://bit.ly/cookmebukkit
configuration:
  permissions: true
  messages: true
  duration:
    min: 15
    max: 30
effects:
  damage: true
  death: true
  venom: true
  hungervenom: true
  hungerdecrease: true
  confusion: true
  blindness: true
  weakness: true
  slowness: true
  slowness_blocks: true
food:
- RAW_BEEF
- RAW_CHICKEN
- RAW_FISH
- PORK
- ROTTEN_FLESH