# For help please refer to http://bit.ly/cookmebukkitdev or http://bit.ly/cookmebukkit
configuration:
  permissions: true
  messages: true
  duration:
    min: 15
    max: 30
  noBlocks: true
  cooldown: 30
effects:
  damage: 8.75
  death: 4.25
  venom: 8.75
  hungervenom: 8.75
  hungerdecrease: 8.75
  confusion: 8.75
  blindness: 8.75
  weakness: 8.75
  slowness: 8.75
  slowness_blocks: 8.75
  instant_damage: 8.75
  refusing: 8.75
food:
- RAW_BEEF
- RAW_CHICKEN
- RAW_FISH
- PORK
- ROTTEN_FLESH