name: CookMe
main: de.dustplanet.cookme.CookMe
version: 1.5
author: xGhOsTkiLLeRx
website: http://bit.ly/cookmebukkitdev
website: http://bit.ly/cookmebukkit
commands:
  cookme:
    description: Handles all the CookMe commands
    usage: /cookme help - to see a list of available commands
permissions:
  cookme.*:
    description: Gives access to all CookMe permissions
    children:
      cookme.reload: true
      cookme.enable.*: true
      cookme.disable.*: true
      cookme.help: true
      cookme.safe: true
      cookme.cooldown: true
      cookme.duration: true
      cookme.set.*: true
  cookme.enable.*:
    description: Gives access to all CookMe enable commands
    children:
      cookme.enable.permissions: true
      cookme.enable.messages: true
  cookme.disable.*:
    description: Gives access to all CookMe disable commands
    children:
      cookme.disable.permissions: true
      cookme.disable.messages: true
  cookme.set.*:
    description: Gives access to all CookMe set commands
    children:
      cookme.set.all: true
      cookme.set.damage: true
      cookme.set.death: true
      cookme.set.venom: true
      cookme.set.confusion: true
      cookme.set.blindness: true
      cookme.set.weakness: true
      cookme.set.slowness: true
      cookme.set.slowness_blocks: true
      cookme.set.hungerdecrease: true
      cookme.set.hungervenom: true
      cookme.set.instant_damage: true
      cookme.set.refusing: true
  cookme.help:
    description: Allows you to see the help
    default: op
  cookme.reload:
    description: Allows you to reload the config
    default: op
  cookme.safe:
    description: Allows you to be safe against the effects
    default: op
  cookme.set.damage:
    description: Allows you to set the damage
    default: op
  cookme.set.death:
    description: Allows you to set the death
    default: op
  cookme.set.venom:
    description: Allows you to set the venom
    default: op
  cookme.set.hungervenom:
    description: Allows you to set the hungervenom
    default: op
  cookme.set.hungerdecrease:
    description: Allows you to set the hungerdecrease
    default: op
  cookme.set.confusion:
    description: Allows you to set the confusion
    default: op
  cookme.set.blindness:
    description: Allows you to set the blindness
    default: op
  cookme.set.weakness:
    description: Allows you to set the weakness
    default: op
  cookme.set.slowness:
    description: Allows you to set the slowness
    default: op
  cookme.set.slowness_blocks:
    description: Allows you to set the slowness for blocks
    default: op
  cookme.set.instant_damage:
    description: Allows you to set the instant_damage
    default: op
  cookme.set.refusing:
    description: Allows you to set the refusing of raw food
    default: op
  cookme.enable.permissions:
    description: Allows you to enable permissions
    default: op
  cookme.enable.messages:
    description: Allows you to enable messages
    default: op
  cookme.disable.permissions:
    description: Allows you to disable permissions
    default: op
  cookme.disable.messages:
    description: Allows you to disable messages
    default: op
  cookme.duration:
    description: Used for duration things
    default: op
  cookme.cooldown:
    description: Used for cooldown things
    default: op